# Generated by Django 5.0.3 on 2024-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "mri_file",
                    models.FileField(blank=True, null=True, upload_to="mri_files/"),
                ),
            ],
        ),
    ]
