# Generated by Django 5.0.3 on 2024-04-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_physician_alter_patient_email_patient_physician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="physician",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="app.physician",
            ),
            preserve_default=False,
        ),
    ]
